### ISSUE TITLE
id问题导致？

### ISSUE THREAD

**Issue by LACERBA** [chenmnkken/gulp-seajs-combo#1]
我的gulpfile.js是这样写的
gulp.task('seajscombo', function() {
    gulp.src("static/module/*_/_.js")
        .pipe(seajsCombo())
        .pipe(gulp.dest('dist/static/module'));
});

生成的合并文件main.js是这样
define('main',['support','showanimation'],function(require,exports,moudle) {});
define('support',function(require, exports, moudule) {});
define('showanimation',['support'],function(require,exports,moudule) {});

但是执行不了，网上查貌似是id问题，请问怎么解决？

**Comment by chenmnkken** [comment]
seajs.use( 'main' )
你是怎么use这个模块的呢

**Comment by chenmnkken** [comment]
另外 gulp.src 中要设置具体的文件路径

**Comment by LACERBA** [comment]
<script>
        seajs.config({
            base: "../dist/",
            alias:{
                '':'static/module/'
            }
        });
        seajs.use("static/module/game/main");
    </script>
这样use

**Comment by LACERBA** [comment]
seajs.config({
            base: "../dist/",
            alias:{
                '':'static/module/'
            }
        });
        seajs.use("static/module/game/main");

**Comment by chenmnkken** [comment]
看下这2个测试文件的对比就知道了
build前：
https://github.com/chenmnkken/gulp-seajs-combo/blob/master/test/src/f.js
build后
https://github.com/chenmnkken/gulp-seajs-combo/blob/master/test/build/f.js

还有对seajs.config的处理规则
build前：
https://github.com/chenmnkken/gulp-seajs-combo/blob/master/test/src/m.js
build后：
https://github.com/chenmnkken/gulp-seajs-combo/blob/master/test/build/m.js

**Comment by LACERBA** [comment]
还有一个问题啊，如图
![gulp](https://cloud.githubusercontent.com/assets/6136146/6385641/89bfee18-bda7-11e4-85d5-992b7c300cf7.jpg)
@chenmnkken 感觉这个更严重啊。。。

**Comment by chenmnkken** [comment]
合并后的模块可以不用严格按照顺序来的，seajs内部会处理，可以正常运行。
