### ISSUE TITLE
seajs.config中alias配置使用绝对路径时gulp-seajs-combo解析路径错误

### ISSUE THREAD

**Issue by bdss58** [chenmnkken/gulp-seajs-combo#11]
![image](https://cloud.githubusercontent.com/assets/5461407/11553830/73fc014a-99cd-11e5-85b6-3b9d81253b16.png)

使用gulp-seajs-combo合并的时候出错：提示找不到某某文件。比如：

图中配置的jQuery的alias，gulp-seajs-combo找这个jQuery的时候 ’路径解析错误’，所以找不到
![image](https://cloud.githubusercontent.com/assets/5461407/11553934/57d9a804-99ce-11e5-9e83-3d44df8ce763.png)

**Comment by chenmnkken** [comment]
`/lib/jquery/xxx` 这类路径相对于web站点来说是根路径，**相对于站点的根路径**，而合并工具只能基于文件系统的路径来解析，所以在使用中请不要使用根路径，或者你可以使用 gulp-seajs-comobo 的`map`配置项来做路径映射。
