### ISSUE TITLE
请问运用该插件合并模块后，需要手动修改html中的js地址吗？

### ISSUE THREAD

**Issue by Dxig** [chenmnkken/gulp-seajs-combo#16]
谢谢您分享开发的插件，很好用，但是小弟有个问题，劳烦您给解答一下。
如题，有没有简便的方式，项目中不同的html用的js路径不同，不可能全部手动修改html吧。
我的想法是用压缩合并后，输出到和原来的文件相同目录结构的文件夹，比如原来是assets/a.js，合并压缩输出到，build/assets/a.js,这样我只需要在seajs-config中配置就可以实现不同的文件加载。请问如何实现输出时把原来的目录也输出过来？提前感谢您的回答。

**Comment by chenmnkken** [comment]
gulp-seats-combo 只是负责将 seajs 的模块进行合并，而你说的将目录也 copy 过去，这个需要使用 gulp 建其他的任务，一个任务肯定满足不了你说的需求。

**Comment by chenmnkken** [comment]
html 中的 js 引用路径也可以写个任务按照规则进行批量修改，但是这和 js 文件的合并无关了。

**Comment by Dxig** [comment]
感谢您的回答，路径的copy通过模糊匹配路径下的文件: [/_/bar-_.js]可以实现，
