### ISSUE TITLE
你好，没有浏览器环境，seajscombo是如何找到seajs.config的？

### ISSUE THREAD

**Issue by Dxig** [chenmnkken/gulp-seajs-combo#17]
你好，没有浏览器环境，seajscombo是如何找到seajs.config的？

**Comment by chenmnkken** [comment]
可以看看这个示例 https://github.com/chenmnkken/gulp-seajs-combo/blob/master/test/src/m.js

**Comment by Dxig** [comment]
alias 和 seajscombo 里的 map 谁优先呢？

**Comment by chenmnkken** [comment]
seajscombo 的 map 配置是基于文件系统的映射，与 seas.config 的 alias 是有区别的。
