### ISSUE TITLE
建议作者可以在配置中自己配置base和paths，而不是让程序去读取seajs.config

### ISSUE THREAD

**Issue by Dxig** [chenmnkken/gulp-seajs-combo#18]
建议作者可以在seajscombo配置中，添加可以自己配置base和paths，而不是让程序去读取seajs.config，因为我在使用过程中总是因为路径匹配导致好多错误。希望可以以当前gulpfile.js目录为基础目录，然后所有的base、paths，以及其他js文件都是基于此路径，（当然，原先以相对路径require的js文件，相对路径配置），这样可以避免好多问题。感谢作者的付出，往采纳！

**Comment by chenmnkken** [comment]
seajs 是在浏览器中运行的，它的路径解析都是基于 HTTP 协议层，和 gulp 基于文件系统的路径解析还是有区别的。所以如果把配置放到 gulpfile 中就会出现在文件系统中能找到，但是在浏览器中就会运行不了，目前只能在原有的配置基础上想办法以求在两个环境中都能运行正常。
