### ISSUE TITLE
报错  帮忙看看

### ISSUE THREAD

**Issue by leekangtaqi** [chenmnkken/gulp-seajs-combo#3]
![image](https://cloud.githubusercontent.com/assets/5259489/6913102/eaae6af4-d7ad-11e4-9cce-a016e97c5b89.png)

![image](https://cloud.githubusercontent.com/assets/5259489/6913089/beadaf1e-d7ad-11e4-98f4-552fb124fd2b.png)

![image](https://cloud.githubusercontent.com/assets/5259489/6913091/c60c2ee8-d7ad-11e4-91e1-a2fe6f9be1f0.png)

![image](https://cloud.githubusercontent.com/assets/5259489/6913093/cba8ee40-d7ad-11e4-81f3-132822ab47bf.png)

**Comment by leekangtaqi** [comment]
开发环境可以，可是gulp-seajs-combo 说 riot+compiler.js找不到，  config中 去掉.js 也报错

**Comment by chenmnkken** [comment]
riot+compiler.js  你确定这种带 + 的写法规范？你把 + 换成其他的连字符试试

**Comment by leekangtaqi** [comment]
riot+compiler.js里面的一些依赖不是由seajs管理的  报错了  我都给放ignore里面了，可是又报了个错

![qq 20150331143638](https://cloud.githubusercontent.com/assets/5259489/6913476/5e6a639e-d7b3-11e4-9483-0394f7bf2b31.png)

**Comment by chenmnkken** [comment]
刚更新了一个版本，修复了在 windows 平台解析 paths 报错的问题，由于很少用 windows，所以一直没测试过。
你更新下新版本试试，test 目录下的所有模块都能在 windows 平台通过测试了。

**Comment by leekangtaqi** [comment]
不行，还是报这个错。三方库（比如jquery）必须要在最外面套个define 的壳子吗？
能在里面用这种方式支持cmd吗？(typeof define === 'function' && define.cmd)
    define(function(require, exports, module) {
      module.exports = riot
    })
还是报那个错
![](https://cloud.githubusercontent.com/assets/5259489/6913476/5e6a639e-d7b3-11e4-9483-0394f7bf2b31.png)

**Comment by chenmnkken** [comment]
你的 seajs.config 有点乱，建议先尽量精简，另外 seajs.config 中不要出现注释，非 CMD 的 js 为什么还要使用 gulp-seajs-combo 呢？

**Comment by leekangtaqi** [comment]
我想把所有的js 都由seajs来管理 啊   随时可以require，最后把所有的js 都打成一个js
gulp-seajs-combo能打包进来三方库吗？

**Comment by chenmnkken** [comment]
建议常用的基础库做合并，比如将 jquery 和 seajs 一开始就做合并，使用一个 script 标签就加载好了，省去了很多麻烦。

**Comment by leekangtaqi** [comment]
为什么我jquery 我都打包不进来呢？

**Comment by leekangtaqi** [comment]
请问，main.js的所有的依赖都要 套 define(function(require, exports, module){
的壳子才能被打包进来吗，立即执行函数里exports不支持是吧

**Comment by chenmnkken** [comment]
非 cmd 模块或者 jquery 这种，都是支持打包的，只是要看你在实际中怎么使用和配置了。
打包时的文件查找策略都是基于 os 中的纯文件系统来的，只要物理文件路径能对上即可，而在实际使用的时候，模块加载时的寻找文件的策略就要复杂的多是基于HTTP协议的。打包工具模拟不出来模块在实际页面中的使用情况，所以就会碰到实际使用或者打包会出问题的情况。
建议尽量规范简洁的使用seajs.config，确保实际使用和打包都在一定的边界内。
