### ISSUE TITLE
關於map配置的問題

### ISSUE THREAD

**Issue by AllenYu0118** [chenmnkken/gulp-seajs-combo#4]
我有很多Widget內的公共JS在Static調用，當合併Static內的JS時就會發現合併不同的JS，就需要不斷的配置seajsCombo里的map，而且有很多需要重複配置，是否可以讓seajsCombo讀取seajs.config內的配置？
![20150512104212](https://cloud.githubusercontent.com/assets/7732447/7579258/925acf8a-f893-11e4-807a-590414e1b3dd.png)

**Comment by AllenYu0118** [comment]
或者seajsCombo是否可以設置一個根目錄？類似seajs.config中的base？

**Comment by chenmnkken** [comment]
可以读取 seajs.config 中的配置，见测试用例 [test/src/m.js](https://github.com/chenmnkken/gulp-seajs-combo/blob/master/test/src/m.js) 和 [test/build/m.js](https://github.com/chenmnkken/gulp-seajs-combo/blob/master/test/build/m.js)

**Comment by AllenYu0118** [comment]
我的配置文件是單獨加載的，沒有和入口文件放一起，如何能讀取單獨的seajs.config文件？

**Comment by chenmnkken** [comment]
入口文件中应该包含 seajs.config，这样才方便处理。

**Comment by AllenYu0118** [comment]
網站雖然不是很大，但是體量也已經到了很多東西不是想改動就能改動的時候了，要不然也不用那麼麻煩了，現在還有一個問題，麻煩先看下圖：
![20150512150613](https://cloud.githubusercontent.com/assets/7732447/7581662/7ef5a0a8-f8b8-11e4-9a29-c6528f6297a9.png)
合併的是list.js這個文件，內部有通過seajs.config配置別名ajaxOnce、lang/static_main、templat...等等公共插件，而這些插件的真實路徑是相對于合併的list.js來配置的，請問是否有方法可以以gulpfile.js配置文件作為根目錄來進行配置？類似seajs.config中的base指定一個根目錄？

**Comment by chenmnkken** [comment]
没有 base 这个配置项，怕 base 太多把用户搞混了。
设置一个 base 并不能解决问题，合并的时候能跑通，但在实际使用的时候不一定就能跑通，所以既要保证可用又要保证可以合并。

**Comment by AllenYu0118** [comment]
通過獲取gulpfile.js的絕對路徑解決了我的部分需求，現在基本可以用，非常感謝你的耐心解答
