### ISSUE TITLE
模块依赖解析函数存在bug

### ISSUE THREAD

**Issue by yuhaoboris** [chenmnkken/gulp-seajs-combo#7]
在使用过程中，发现存在一些特殊情况，combo对模块的依赖解析出错。
当标准的seajs模块中存在<code>seajs.use</code>调用时，依赖解析会跳去解析seajs.use的模式

``` javascript
defind(function(require, exports, module) {
    var $ = require('jQuery');
    function doSomething() {
        seajs.use('http://hm.baidu.com/h.js');
    }
})
```

**Comment by chenmnkken** [comment]
你应该没有仔细看 seajs 的[官方文档](https://github.com/seajs/seajs/issues/260)
`seajs.use` 理论上只用于加载启动，不应该出现在 `define` 中的模块代码里。在模块代码里需要异步加载其他模块时，推荐使用 `require.async` 方法。

**Comment by yuhaoboris** [comment]
噢，对，还好你提醒一下。谢谢！

**Comment by yuhaoboris** [comment]
补充一下：如果在多行注释里面存在<code>seajs.use</code>，也会跳去解析seajs.use模式。

**Comment by ghost** [comment]
@borisyu 哥们，你模块里面有依赖 html模块吗？ 我现在加载html模块时候报错。gulp-seajs-cmobo Error: TypeError: Cannot read property 'forEach' of undefined

**Comment by yuhaoboris** [comment]
@xushao0305 这个错误信息跟你是否加载html模块无关，我之前也有出现这种错误，debug后发现是在解析依赖模块的过程中出错的。你最好debug一下看看到底在哪个环节报错了。

**Comment by ghost** [comment]
OK.后面是发现html引入了underscore模块导致的，原声的seajs-text不支持underscore模板语法。
