### ISSUE TITLE
require压缩报错

### ISSUE THREAD

**Issue by jssoscar** [chenmnkken/gulp-seajs-combo#9]
代码中是这样require一个模块：
Hogan.compile(require("./template"))

但是压缩后：
Hogan.compilerequire('template'))

压缩后直接报错。
然后改为：var template = require("./template")方式压缩即可。
如此看来，插件是不支持非变量方式的require。

**Comment by jssoscar** [comment]
自己对seajs看的不够自习，对于require，必须是开头使用require。
其他地方对require的使用，必须通过异步方式来调用。

**Comment by chenmnkken** [comment]
SeaJS会使用正则的形式去匹配依赖，它并不会将require('xxx')替换成一个变量
